import { type Alert } from './types';

export const initialAlerts: Alert[] = [
  {
    id: 'alert-1',
    time: '2025-09-29T12:02:15Z',
    host: 'WIN-CLIENT-01',
    alertType: 'NetworkAnomaly',
    score: 0.92,
    mitreTactic: 'TA0010', // Exfiltration
    srcIp: '10.0.0.5',
    dstIp: '93.184.216.34',
    evidence: 'bytes=180432; s3_upload=yes',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.85,
    supervisedClassifierScore: 0.95,
    topRuleHits: ['Large Outbound Transfer', 'S3 Upload Pattern'],
    topFeatures: ['byte_count', 'dst_port_443', 'is_s3_domain'],
  },
  {
    id: 'alert-2',
    time: '2025-09-29T11:48:02Z',
    host: 'WIN-CLIENT-01',
    alertType: 'ProcessAnomaly',
    score: 0.87,
    mitreTactic: 'TA0001', // Initial Access
    srcIp: '10.0.0.5',
    dstIp: '-',
    evidence: 'winword -> powershell -> curl',
    status: 'New',
    ruleBasedScore: 0.9,
    anomalyDetectionScore: 0.7,
    supervisedClassifierScore: 0.88,
    topRuleHits: ['Suspicious Process Chain'],
    topFeatures: ['parent_process:winword.exe', 'child_process:powershell.exe', 'network_connection:curl.exe'],
  },
  {
    id: 'alert-3',
    time: '2025-09-29T11:40:12Z',
    host: 'DB-SERVER-01',
    alertType: 'LateralMovement',
    score: 0.76,
    mitreTactic: 'TA0008', // Lateral Movement
    srcIp: '10.0.0.8',
    dstIp: '10.0.0.12',
    evidence: 'smb auth failed then success',
    status: 'Investigating',
    ruleBasedScore: 0.6,
    anomalyDetectionScore: 0.8,
    supervisedClassifierScore: 0.7,
    topRuleHits: ['Brute-force attempt', 'SMB Connection'],
    topFeatures: ['auth_failures', 'subsequent_auth_success', 'protocol:smb'],
  },
  {
    id: 'alert-4',
    time: '2025-09-29T11:25:33Z',
    host: 'WORKSTATION-05',
    alertType: 'Beaconing',
    score: 0.64,
    mitreTactic: 'TA0003', // Persistence
    srcIp: '10.0.0.14',
    dstIp: '198.51.100.10',
    evidence: 'periodic 60s dns TXT requests',
    status: 'New',
    ruleBasedScore: 0.7,
    anomalyDetectionScore: 0.6,
    supervisedClassifierScore: 0.5,
    topRuleHits: ['Periodic DNS Beaconing'],
    topFeatures: ['interval_std_dev:0.1s', 'dns_query_type:TXT', 'payload_size:small'],
  },
  {
    id: 'alert-5',
    time: '2025-09-29T11:10:05Z',
    host: 'WIN-CLIENT-01',
    alertType: 'FileAccess',
    score: 0.55,
    mitreTactic: 'TA0005', // Discovery
    srcIp: '-',
    dstIp: '-',
    evidence: 'many read ops on C:\\\\Secrets',
    status: 'Resolved',
    ruleBasedScore: 0.4,
    anomalyDetectionScore: 0.5,
    supervisedClassifierScore: 0.6,
    topRuleHits: ['High-frequency file access'],
    topFeatures: ['file_path:C:\\Secrets', 'operation_count_read:high', 'process:explorer.exe'],
  },
];
